#!/usr/bin/env bash
if [ -f .env ]; then
  sed -i 's/\r$//' .env || true
  set -a
  source .env
  set +a
fi

export PORT=${PORT:-4000}
export DB_TYPE=${DB_TYPE:-mariadb}
export DB_HOST=${DB_HOST:-localhost}
export DB_PORT=${DB_PORT:-3306}
export DB_USER=${DB_USER:-root}
export DB_PASS=${DB_PASS:-}
export DB_NAME=${DB_NAME:-panel}
export DATABASE_URL=${DATABASE_URL:-}

export JWT_SECRET=${JWT_SECRET:-super-secret-string}
export WINGS_URL=${WINGS_URL:-http://localhost:8080}
export WINGS_TOKEN=${WINGS_TOKEN:-wingstoken123}
export PDNS_BASE_URL=${PDNS_BASE_URL:-http://127.0.0.1:8081/api/v1/servers/localhost}
export PDNS_API_KEY=${PDNS_API_KEY:-abcd1234-powerdns-key}
export REDIS_URL=${REDIS_URL:-redis://localhost:6379}

export ORIGIN=${ORIGIN:-https://ecli.app}
export RP_ID=${RP_ID:-ecli.app}

export GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-grrr}
export GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-grrr}

export EU_ID_DISABLED=${EU_ID_DISABLED:-true}

export CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-""}
export CLOUDFLARE_BASE_ZONE=${CLOUDFLARE_BASE_ZONE:-""}
export CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID:-""}

export HACKCLUB_CLIENT_ID=${HACKCLUB_CLIENT_ID:-""}
export HACKCLUB_CLIENT_SECRET=${HACKCLUB_CLIENT_SECRET:-""}
export HACKCLUB_REDIRECT_URI=${HACKCLUB_REDIRECT_URI:-""}

export CAPTCHA_SECRET=${CAPTCHA_SECRET:-""}

export MAILCOW_API_URL=${MAILCOW_API_URL:-""}
export MAILCOW_API_KEY=${MAILCOW_API_KEY:-""}
export MAILBOX_DOMAIN=${MAILBOX_DOMAIN:-""}
export MAIL_DOMAIN=${MAIL_DOMAIN:-""}
export MAILBOX_INBOUND_SECRET=${MAILBOX_INBOUND_SECRET:-""}
export MAILCOW_TIMEOUT_MS=${MAILCOW_TIMEOUT_MS:-30000}
export MAILCOW_RETRIES=${MAILCOW_RETRIES:-2}

export MAILBOX_SMTP_HOST=${MAILBOX_SMTP_HOST:-mail.${MAILBOX_DOMAIN}}
export MAILBOX_SMTP_PORT=${MAILBOX_SMTP_PORT:-587}
export MAILBOX_SMTP_SECURE=${MAILBOX_SMTP_SECURE:-false}
export MAILBOX_IMAP_HOST=${MAILBOX_IMAP_HOST:-mail.${MAILBOX_DOMAIN}}
export MAILBOX_IMAP_PORT=${MAILBOX_IMAP_PORT:-993}
export MAILBOX_IMAP_SECURE=${MAILBOX_IMAP_SECURE:-true}

export SMTP_HOST=${SMTP_HOST:-127.0.0.1}
export SMTP_PORT=${SMTP_PORT:-465}
export SMTP_SECURE=${SMTP_SECURE:-true}
export SMTP_USER=${SMTP_USER:-}
export SMTP_PASS=${SMTP_PASS:-}
export SMTP_TLS_ALLOW_INVALID=${SMTP_TLS_ALLOW_INVALID:-false}
export SMTP_FROM=${SMTP_FROM:-""}

export DOVECOT_MASTER_USER=${DOVECOT_MASTER_USER:-""}
export DOVECOT_MASTER_PASS=${DOVECOT_MASTER_PASS:-""}
export DOVECOT_MASTER_DOMAIN=${DOVECOT_MASTER_DOMAIN:-""}
export IMAP_FETCH_CRON=${IMAP_FETCH_CRON:-""}

export NODE_ENCRYPTION_KEY=${NODE_ENCRYPTION_KEY:-""}
export NODE_PQ_ENCRYPTION_SEED=${NODE_PQ_ENCRYPTION_SEED:-""}

echo "--- environment loaded ---"

if command -v bun >/dev/null 2>&1; then
  bun src/index.ts
fi
