import { Elysia } from 'elysia';

import { userRoutes } from '../handlers/userHandler';
import { sessionRoutes } from '../handlers/sessionHandler';
import { authRoutes } from '../handlers/authHandler';
import { logRoutes } from '../handlers/logHandler';
import { idVerificationRoutes } from '../handlers/idVerificationHandler';
import { deletionRoutes } from '../handlers/deletionHandler';
import { roleRoutes } from '../handlers/roleHandler';
import { organisationRoutes } from '../handlers/organisationHandler';
import { orderRoutes } from '../handlers/orderHandler';
import { socRoutes } from '../handlers/socHandler';
import { aiRoutes } from '../handlers/aiHandler';
import { serverRoutes } from '../handlers/serverHandler';
import { nodeRoutes } from '../handlers/nodeHandler';
import { apiKeyRoutes } from '../handlers/apiKeyHandler';
import { ticketRoutes } from '../handlers/ticketHandler';
import { adminRoutes } from '../handlers/adminHandler';
import { eggRoutes } from '../handlers/eggHandler';
import { remoteRoutes } from '../handlers/remoteHandler';
import { oauthRoutes, oauthWellKnownRoutes } from '../handlers/oauthHandler';
import { databaseRoutes } from '../handlers/databaseHandler';
import { planRoutes } from '../handlers/planHandler';
import { serverSubuserRoutes } from '../handlers/serverSubuserHandler';
import { wsProxyRoutes } from '../handlers/wsProxyHandler';
import { sshKeyRoutes } from '../handlers/sshKeyHandler';
import { publicRoutes } from '../handlers/publicHandler';
// Migrating  to Elysia was a mistake but now its bulletproof?
export function registerRoutes(app: any) {
    app.get('/favicon.ico', () => new Response(null, { status: 204 }));
    userRoutes(app, '/api');
    sessionRoutes(app, '/api');
    authRoutes(app, '/api');
    logRoutes(app, '/api');
    deletionRoutes(app, '/api');
    idVerificationRoutes(app, '/api');
    roleRoutes(app, '/api');
    organisationRoutes(app, '/api');
    orderRoutes(app, '/api');
    socRoutes(app, '/api');
    aiRoutes(app, '/api');
    serverRoutes(app, '/api');
    nodeRoutes(app, '/api');
    apiKeyRoutes(app, '/api');
    ticketRoutes(app, '/api');
    adminRoutes(app, '/api');
    eggRoutes(app, '/api');
    remoteRoutes(app, '/api');
    oauthRoutes(app, '/api');
    oauthWellKnownRoutes(app, '/api');
    databaseRoutes(app, '/api');
    planRoutes(app, '/api');
    wsProxyRoutes(app, '/api');
    sshKeyRoutes(app, '/api');
    serverSubuserRoutes(app, '/api');
    publicRoutes(app, '');
}