"use client"

import { useEffect, useState, useRef, lazy, Suspense } from "react"
import { apiFetch } from "@/lib/api-client"
import { API_ENDPOINTS } from "@/lib/panel-config"
import { DEFAULT_EDITOR_SETTINGS, type EditorSettings } from "@/lib/editor-settings"
import { Loader2 } from "lucide-react"

const MonacoEditor = lazy(() => import("@monaco-editor/react").then((m) => ({ default: m.default })))

export function MonacoFileEditor({ value, onChange, language, editorSettings }: { value: string; onChange: (v: string | undefined) => void; language: string; editorSettings?: EditorSettings }) {
  const settings = { ...DEFAULT_EDITOR_SETTINGS, ...(editorSettings || {}) }
  const [aiLoading, setAiLoading] = useState(false)
  const editorRef = useRef<any | null>(null)
  const monacoRef = useRef<any | null>(null)
  const providerRef = useRef<any | null>(null)
  const aiCacheRef = useRef<{ key: string; promise: Promise<any> | null; result: any | null }>({ key: '', promise: null, result: null })

  const stripCodeFences = (text: string) => {
    return text.replace(/^\s*```\w*\n/, '').replace(/\n```\s*$/, '').trimEnd()
  }

  const settingsRef = useRef(settings)
  const [editorReady, setEditorReady] = useState(false)

  useEffect(() => {
    settingsRef.current = settings
  }, [settings])

  useEffect(() => {
    if (!editorReady || !monacoRef.current || !editorRef.current) return

    providerRef.current?.dispose()
    providerRef.current = null
    aiCacheRef.current = { key: '', promise: null, result: null }

    const currentSettings = settingsRef.current
    if (!currentSettings.aiAssistant) return

    providerRef.current = monacoRef.current.languages.registerCompletionItemProvider(language, {
      triggerCharacters: ['.', '(', ' ', '\t', '=', ',', '+', '-'],
      provideCompletionItems: async (model: any, position: any) => {
        const cursorOffset = model.getOffsetAt(position)
        const maxContext = 2000
        const fullText = model.getValue()
        const contextText = fullText.slice(Math.max(0, cursorOffset - maxContext), cursorOffset)
        const key = `${language}:${contextText}`

        if (aiCacheRef.current.key === key && aiCacheRef.current.result) {
          return aiCacheRef.current.result
        }
        if (aiCacheRef.current.key === key && aiCacheRef.current.promise) {
          return aiCacheRef.current.promise
        }

        const promise = (async () => {
          const prompt = `Complete the following code at the cursor position. Only return the code to insert (no explanations):\n\n${contextText}`
          setAiLoading(true)
          try {
            const response = await apiFetch(API_ENDPOINTS.aiChat, {
              method: 'POST',
              body: JSON.stringify({ message: prompt }),
            })

            const raw = String(response.reply || '')
            const completion = stripCodeFences(raw).trim()
            if (!completion) {
              const empty = { suggestions: [] }
              aiCacheRef.current = { key, promise: null, result: empty }
              return empty
            }

            const insertText = completion.trim()
            if (!insertText) {
              const empty = { suggestions: [] }
              aiCacheRef.current = { key, promise: null, result: empty }
              return empty
            }

            const snippet = insertText.split('\n')[0].trim()
            const label = snippet.length > 0 ? (snippet.length > 60 ? snippet.slice(0, 57) + '...' : snippet) : 'AI suggestion'

            const item = {
              label,
              kind: monacoRef.current.languages.CompletionItemKind.Snippet,
              insertText,
              insertTextRules: monacoRef.current.languages.CompletionItemInsertTextRule.InsertAsSnippet,
              detail: 'AI suggestion',
              documentation: 'Generated by AI',
            }

            const result = { suggestions: [item] }
            aiCacheRef.current = { key, promise: null, result }
            return result
          } catch (err) {
            const empty = { suggestions: [] }
            aiCacheRef.current = { key, promise: null, result: empty }
            return empty
          } finally {
            setAiLoading(false)
          }
        })()

        aiCacheRef.current = { key, promise, result: null }
        return promise
      },
      resolveCompletionItem: (item: any) => item,
    })

    return () => {
      providerRef.current?.dispose()
      providerRef.current = null
      aiCacheRef.current = { key: '', promise: null, result: null }
    }
  }, [language, settings.aiAssistant, editorReady])

  return (
    <Suspense fallback={<div className="flex items-center justify-center h-[600px] bg-[#1e1e1e]"><Loader2 className="h-5 w-5 animate-spin text-muted-foreground" /></div>}>
      <MonacoEditor
        height="600px"
        language={language}
        value={value}
        onChange={onChange}
        theme="vs-dark"
        onMount={(editor, monaco) => {
          editorRef.current = editor
          monacoRef.current = monaco
          setEditorReady(true)

          const suggestDebounce = { id: 0 } as { id: number }
          editor.onDidChangeModelContent((e: any) => {
            if (!settingsRef.current.aiAssistant) return
            if (!e.changes || e.changes.length === 0) return
            const lastChange = e.changes[e.changes.length - 1]
            const text = lastChange.text || ''
            if (!text) return
            clearTimeout(suggestDebounce.id)
            suggestDebounce.id = window.setTimeout(() => {
              editor.trigger('keyboard', 'editor.action.triggerSuggest', {})
            }, 150)
          })
        }}
        options={{
          minimap: { enabled: !!settings.minimap },
          fontSize: settings.fontSize,
          fontFamily: settings.fontFamily,
          scrollBeyondLastLine: false,
          wordWrap: "on",
          lineNumbers: "on",
          renderWhitespace: "selection",
          tabSize: settings.tabSize,
          insertSpaces: settings.insertSpaces,
          autoIndent: settings.autoIndent ? "full" : "none",
          formatOnType: settings.formatOnType,
          formatOnPaste: settings.formatOnPaste,
          padding: { top: 12 },
          inlineSuggest: { enabled: !!settings.aiAssistant },
          quickSuggestions: !!settings.aiAssistant,
          acceptSuggestionOnEnter: settings.aiAssistant ? "on" : "off",
        }}
      />
    </Suspense>
  )
}
